/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.3.57
* Mon Jun 18 17:18:03 CEST 2012
* Mission file name: FPBasicTraining.Chernarus
* Mission name: FPBasicTraining.Chernarus
* Required mods:
* + ACE
* + ACRE
* + OA
* 
* Call the script: _dummy = [] execvm "lea\loadout-solo.sqf";
* 
*/

/**
* Loadout for vehicles
*/

//No named vehicles in this mission.

/**
* Loadout for ai units
*/

//No named AI units in this mission.

/**
* Loadout for playable units
*/


  removeallweapons s1;
  removeallitems s1;
  removeBackpack s1;

  _s1playerweap = [
	 "ACE_M4A1_HWS_GL_F",
	 "ACRE_PRC117F",
	 "ACE_Rangefinder_OD",
	 "ACRE_PRC148_UHF",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_DAGR",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ACE_HuntIR_monitor",
	 "ItemMap",
	 "ACE_GlassesTactical",
	  "ItemWatch"
	 ];

  _s1playerammo = [
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "ACE_30Rnd_556x45_T_Stanag",
	 "ACE_30Rnd_556x45_T_Stanag",
	 "ACE_30Rnd_556x45_T_Stanag",
	 "ACE_30Rnd_556x45_T_Stanag",
	 "ACE_30Rnd_556x45_T_Stanag",
	 "ACE_30Rnd_556x45_T_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "ACE_HuntIR_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_Smoke_M203",
	 "ACE_Bandage",
	 "ACE_Bandage",
	 "ACE_Morphine",
	 "ACE_Epinephrine",
	  "ACE_Epinephrine"
	 ];

  _s1playerweapback = "";

  _s1playerweapruck = [];
  _s1playerammoruck = [];
  s1 setvariable ["ACE_weapononback", _s1playerweapback];
  {s1 addmagazine _x} foreach _s1playerammo;
  {s1 addWeapon _x} foreach _s1playerweap;

  s1 selectWeapon (primaryWeapon s1);

  removeallweapons s2;
  removeallitems s2;
  removeBackpack s2;

  _s2playerweap = [
	 "ACE_M4A1_Eotech",
	 "ACE_Rucksack_MOLLE_Brown_Medic",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	 "ACE_GlassesTactical",
	  "ItemWatch"
	 ];

  _s2playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "SmokeShellOrange",
	 "SmokeShellOrange",
	 "ACE_Bandage",
	 "ACE_Bandage",
	 "ACE_LargeBandage",
	 "ACE_LargeBandage",
	 "ACE_Epinephrine",
	 "ACE_Morphine",
	 "ACE_Bandage",
	 "ACE_Bandage",
	 "ACE_Morphine",
	 "ACE_Epinephrine",
	  "ACE_Epinephrine"
	 ];

  _s2playerweapback = "";

  _s2playerweapruck = [];
  _s2playerammoruck = [["ACE_Bandage",10],["ACE_Epinephrine",15],["ACE_LargeBandage",15],["ACE_Medkit",10],["ACE_Morphine",19]];
  s2 setvariable ["ACE_RuckMagContents", _s2playerammoruck];
  s2 setvariable ["ACE_weapononback", _s2playerweapback];
  {s2 addmagazine _x} foreach _s2playerammo;
  {s2 addWeapon _x} foreach _s2playerweap;

  s2 selectWeapon (primaryWeapon s2);

  removeallweapons s3;
  removeallitems s3;
  removeBackpack s3;

  _s3playerweap = [
	 "M4A1_HWS_GL",
	 "M136",
	 "ACE_Rangefinder_OD",
	 "ACRE_PRC148_UHF",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_DAGR",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ACE_HuntIR_monitor",
	 "ItemMap",
	 "ACE_GlassesTactical",
	  "ItemWatch"
	 ];

  _s3playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "ACE_30Rnd_556x45_T_Stanag",
	 "ACE_30Rnd_556x45_T_Stanag",
	 "ACE_HuntIR_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_Smoke_M203",
	 "ACE_Bandage",
	 "ACE_Bandage",
	 "ACE_Morphine",
	 "ACE_Epinephrine",
	  "ACE_Epinephrine"
	 ];

  _s3playerweapback = "";

  _s3playerweapruck = [];
  _s3playerammoruck = [];
  s3 setvariable ["ACE_weapononback", _s3playerweapback];
  {s3 addmagazine _x} foreach _s3playerammo;
  {s3 addWeapon _x} foreach _s3playerweap;

  s3 selectWeapon (primaryWeapon s3);

  removeallweapons s4;
  removeallitems s4;
  removeBackpack s4;

  _s4playerweap = [
	 "ACE_M4A1_ACOG_F",
	 "ACE_VTAC_RUSH72",
	 "ACE_P226",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	 "ACE_GlassesTactical",
	  "ItemWatch"
	 ];

  _s4playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "ACE_30Rnd_556x45_T_Stanag",
	 "ACE_30Rnd_556x45_T_Stanag",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_Bandage",
	 "ACE_Bandage",
	 "ACE_Morphine",
	 "ACE_Epinephrine",
	  "ACE_Epinephrine"
	 ];

  _s4playerweapback = "";

  _s4playerweapruck = [];
  _s4playerammoruck = [["PipeBomb",1],["ACE_C4_M",4],["30Rnd_556x45_Stanag",6]];
  s4 setvariable ["ACE_RuckMagContents", _s4playerammoruck];
  s4 setvariable ["ACE_weapononback", _s4playerweapback];
  {s4 addmagazine _x} foreach _s4playerammo;
  {s4 addWeapon _x} foreach _s4playerweap;

  s4 selectWeapon (primaryWeapon s4);

  removeallweapons s5;
  removeallitems s5;
  removeBackpack s5;

  _s5playerweap = [
	 "M249_EP1",
	 "ACE_P226",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	 "ACE_GlassesTactical",
	  "ItemWatch"
	 ];

  _s5playerammo = [
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "ACE_200Rnd_556x45_T_M249",
	 "ACE_200Rnd_556x45_T_M249",
	 "ACE_200Rnd_556x45_T_M249",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_Bandage",
	 "ACE_Bandage",
	 "ACE_Morphine",
	 "ACE_Epinephrine",
	  "ACE_Epinephrine"
	 ];

  _s5playerweapback = "";

  _s5playerweapruck = [];
  _s5playerammoruck = [];
  s5 setvariable ["ACE_weapononback", _s5playerweapback];
  {s5 addmagazine _x} foreach _s5playerammo;
  {s5 addWeapon _x} foreach _s5playerweap;

  s5 selectWeapon (primaryWeapon s5);

  removeallweapons s6;
  removeallitems s6;
  removeBackpack s6;

  _s6playerweap = [
	 "ACE_M4A1_Eotech",
	 "ACE_CharliePack_ACU",
	 "ACE_P226",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	 "ACE_GlassesTactical",
	  "ItemWatch"
	 ];

  _s6playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_Bandage",
	 "ACE_Bandage",
	 "ACE_Morphine",
	 "ACE_Epinephrine",
	  "ACE_Epinephrine"
	 ];

  _s6playerweapback = "";

  _s6playerweapruck = [];
  _s6playerammoruck = [["ACE_200Rnd_556x45_T_M249",3]];
  s6 setvariable ["ACE_RuckMagContents", _s6playerammoruck];
  s6 setvariable ["ACE_weapononback", _s6playerweapback];
  {s6 addmagazine _x} foreach _s6playerammo;
  {s6 addWeapon _x} foreach _s6playerweap;

  s6 selectWeapon (primaryWeapon s6);

  removeallweapons s7;
  removeallitems s7;
  removeBackpack s7;

  _s7playerweap = [
	 "M4A1_HWS_GL",
	 "M136",
	 "ACE_Rangefinder_OD",
	 "ACRE_PRC148_UHF",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_DAGR",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ACE_HuntIR_monitor",
	 "ItemMap",
	 "ACE_GlassesTactical",
	  "ItemWatch"
	 ];

  _s7playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "ACE_30Rnd_556x45_T_Stanag",
	 "ACE_30Rnd_556x45_T_Stanag",
	 "ACE_HuntIR_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_Smoke_M203",
	 "ACE_Bandage",
	 "ACE_Bandage",
	 "ACE_Morphine",
	 "ACE_Epinephrine",
	  "ACE_Epinephrine"
	 ];

  _s7playerweapback = "";

  _s7playerweapruck = [];
  _s7playerammoruck = [];
  s7 setvariable ["ACE_weapononback", _s7playerweapback];
  {s7 addmagazine _x} foreach _s7playerammo;
  {s7 addWeapon _x} foreach _s7playerweap;

  s7 selectWeapon (primaryWeapon s7);

  removeallweapons s8;
  removeallitems s8;
  removeBackpack s8;

  _s8playerweap = [
	 "ACE_M27_IAR",
	 "ACE_P226",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	 "ACE_GlassesTactical",
	  "ItemWatch"
	 ];

  _s8playerammo = [
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_Bandage",
	 "ACE_Bandage",
	 "ACE_Morphine",
	 "ACE_Epinephrine",
	  "ACE_Epinephrine"
	 ];

  _s8playerweapback = "ACE_WireCutter";

  _s8playerweapruck = [];
  _s8playerammoruck = [];
  s8 setvariable ["ACE_weapononback", _s8playerweapback];
  {s8 addmagazine _x} foreach _s8playerammo;
  {s8 addWeapon _x} foreach _s8playerweap;

  s8 selectWeapon (primaryWeapon s8);

  removeallweapons s9;
  removeallitems s9;
  removeBackpack s9;

  _s9playerweap = [
	 "ACE_M4A1_Eotech",
	 "MAAWS",
	 "ACE_P226",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	 "ACE_GlassesTactical",
	  "ItemWatch"
	 ];

  _s9playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "MAAWS_HEDP",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_Bandage",
	 "ACE_Bandage",
	 "ACE_Morphine",
	 "ACE_Epinephrine",
	  "ACE_Epinephrine"
	 ];

  _s9playerweapback = "";

  _s9playerweapruck = [];
  _s9playerammoruck = [];
  s9 setvariable ["ACE_weapononback", _s9playerweapback];
  {s9 addmagazine _x} foreach _s9playerammo;
  {s9 addWeapon _x} foreach _s9playerweap;

  s9 selectWeapon (primaryWeapon s9);

  removeallweapons s10;
  removeallitems s10;
  removeBackpack s10;

  _s10playerweap = [
	 "ACE_M4A1_Eotech",
	 "ACE_Backpack_US",
	 "ACE_P226",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	 "ACE_GlassesTactical",
	  "ItemWatch"
	 ];

  _s10playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_Bandage",
	 "ACE_Bandage",
	 "ACE_Morphine",
	 "ACE_Epinephrine",
	  "ACE_Epinephrine"
	 ];

  _s10playerweapback = "";

  _s10playerweapruck = [];
  _s10playerammoruck = [["ACE_MAAWS_HE",2],["MAAWS_HEAT",2]];
  s10 setvariable ["ACE_RuckMagContents", _s10playerammoruck];
  s10 setvariable ["ACE_weapononback", _s10playerweapback];
  {s10 addmagazine _x} foreach _s10playerammo;
  {s10 addWeapon _x} foreach _s10playerweap;

  s10 selectWeapon (primaryWeapon s10);

  removeallweapons s11;
  removeallitems s11;
  removeBackpack s11;

  _s11playerweap = [
	 "M4A1_HWS_GL",
	 "M136",
	 "ACE_Rangefinder_OD",
	 "ACRE_PRC148_UHF",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_DAGR",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ACE_HuntIR_monitor",
	 "ItemMap",
	 "ACE_GlassesTactical",
	  "ItemWatch"
	 ];

  _s11playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "ACE_30Rnd_556x45_T_Stanag",
	 "ACE_30Rnd_556x45_T_Stanag",
	 "ACE_HuntIR_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_Smoke_M203",
	 "ACE_Bandage",
	 "ACE_Bandage",
	 "ACE_Morphine",
	 "ACE_Epinephrine",
	  "ACE_Epinephrine"
	 ];

  _s11playerweapback = "";

  _s11playerweapruck = [];
  _s11playerammoruck = [];
  s11 setvariable ["ACE_weapononback", _s11playerweapback];
  {s11 addmagazine _x} foreach _s11playerammo;
  {s11 addWeapon _x} foreach _s11playerweap;

  s11 selectWeapon (primaryWeapon s11);

  removeallweapons s12;
  removeallitems s12;
  removeBackpack s12;

  _s12playerweap = [
	 "ACE_M4A1_ACOG_F",
	 "ACE_VTAC_RUSH72",
	 "ACE_P226",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	 "ACE_GlassesTactical",
	  "ItemWatch"
	 ];

  _s12playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "ACE_30Rnd_556x45_T_Stanag",
	 "ACE_30Rnd_556x45_T_Stanag",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_Bandage",
	 "ACE_Bandage",
	 "ACE_Morphine",
	 "ACE_Epinephrine",
	  "ACE_Epinephrine"
	 ];

  _s12playerweapback = "";

  _s12playerweapruck = [];
  _s12playerammoruck = [["PipeBomb",1],["ACE_C4_M",4],["30Rnd_556x45_Stanag",6]];
  s12 setvariable ["ACE_RuckMagContents", _s12playerammoruck];
  s12 setvariable ["ACE_weapononback", _s12playerweapback];
  {s12 addmagazine _x} foreach _s12playerammo;
  {s12 addWeapon _x} foreach _s12playerweap;

  s12 selectWeapon (primaryWeapon s12);

  removeallweapons s13;
  removeallitems s13;
  removeBackpack s13;

  _s13playerweap = [
	 "M249_EP1",
	 "ACE_P226",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	 "ACE_GlassesTactical",
	  "ItemWatch"
	 ];

  _s13playerammo = [
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "ACE_200Rnd_556x45_T_M249",
	 "ACE_200Rnd_556x45_T_M249",
	 "ACE_200Rnd_556x45_T_M249",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_Bandage",
	 "ACE_Bandage",
	 "ACE_Morphine",
	 "ACE_Epinephrine",
	  "ACE_Epinephrine"
	 ];

  _s13playerweapback = "";

  _s13playerweapruck = [];
  _s13playerammoruck = [];
  s13 setvariable ["ACE_weapononback", _s13playerweapback];
  {s13 addmagazine _x} foreach _s13playerammo;
  {s13 addWeapon _x} foreach _s13playerweap;

  s13 selectWeapon (primaryWeapon s13);

  removeallweapons s14;
  removeallitems s14;
  removeBackpack s14;

  _s14playerweap = [
	 "ACE_M4A1_Eotech",
	 "ACE_CharliePack_ACU",
	 "ACE_P226",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	 "ACE_GlassesTactical",
	  "ItemWatch"
	 ];

  _s14playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_Bandage",
	 "ACE_Bandage",
	 "ACE_Morphine",
	 "ACE_Epinephrine",
	  "ACE_Epinephrine"
	 ];

  _s14playerweapback = "";

  _s14playerweapruck = [];
  _s14playerammoruck = [["ACE_200Rnd_556x45_T_M249",3]];
  s14 setvariable ["ACE_RuckMagContents", _s14playerammoruck];
  s14 setvariable ["ACE_weapononback", _s14playerweapback];
  {s14 addmagazine _x} foreach _s14playerammo;
  {s14 addWeapon _x} foreach _s14playerweap;

  s14 selectWeapon (primaryWeapon s14);