/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.3.61
* Sun Jul 15 10:00:53 CEST 2012
* Mission file name: co28@nitrogencold.Woodland_ACR
* Mission name: co28@nitrogencold.Woodland_ACR
* Required mods:
* + ACE
* + ACRE
* 
* Call the script: _dummy = [] execvm "lea\loadout-solo.sqf";
* 
*/

/**
* Loadout for vehicles

AMMO: [["M4A1","M4A3_CCO_EP1","CZ805_A1_ACR","Sa58P_EP1","Sa58V_EP1","Sa58V_RCO_EP1","Sa58V_CCO_EP1","M60A4_EP1","MAAWS","SVD_des_EP1","m107","Sa61_EP1","RPG7V","CZ_75_P_07_DUTY","CZ_75_D_COMPACT","CZ_75_SP_01_PHANTOM",
"CZ_75_SP_01_PHANTOM_SD","Evo_ACR","Evo_mrad_ACR","evo_sd_ACR","UK59_ACR","SVD","Igla","M249_m145_EP1","CZ_750_S1_ACR","CZ805_A1_ACR","CZ805_A1_GL_ACR","CZ805_A2_ACR","CZ805_A2_SD_ACR","CZ805_B_GL_ACR","LRTV_ACR"]
,[4,4,4,4,4,4,4,2,2,2,1,2,2,2,2,2,2,2,2,2,2,4,2,2,2,2,2,2,2,2,1]], 
MAG: 30Rnd_556x45_G36 30Rnd_556x45_G36
[["30Rnd_556x45_G36","100Rnd_762x51_M240","30Rnd_762x39_SA58","1Rnd_HE_M203","HandGrenade_West","SmokeShellRed","SmokeShellGreen","SmokeShellYellow","SmokeShell","MAAWS_HEAT","MAAWS_HEDP","10Rnd_762x54_SVD","30Rnd_556x45_G36SD","30Rnd_556x45_G36",
"30Rnd_556x45_G36SD","10Rnd_127x99_m107","PG7V","PG7VR","Igla","1Rnd_Smoke_M203","1Rnd_SmokeRed_M203","1Rnd_SmokeGreen_M203","1Rnd_SmokeYellow_M203","FlareWhite_M203","FlareGreen_M203","FlareRed_M203","FlareYellow_M203","20Rnd_762x51_B_SCAR",
"20Rnd_762x51_SB_SCAR","100Rnd_762x54_PK","100Rnd_762x54_PK","18Rnd_9x19_Phantom","18Rnd_9x19_PhantomSD","15Rnd_9x19_M9","15Rnd_9x19_M9SD","10Rnd_9x19_Compact","20Rnd_9x19_EVOSD","20Rnd_9x19_EVO","10Rnd_762x51_CZ750","20Rnd_B_765x17_Ball",
"10Rnd_B_765x17_Ball","200Rnd_556x45_M249","Laserbatteries"],[100,50,100,30,50,2,2,2,5,10,10,100,20,200,10,10,15,5,10,2,2,2,2,2,2,2,2,20,20,3,100,20,20,20,20,20,20,20,10,100,100,100,5]]
*/

//No named vehicles in this mission.

/**
* Loadout for ai units
*/

//No named AI units in this mission.

/**
* Loadout for playable units
*/


  removeallweapons s1;
  removeallitems s1;
  removeBackpack s1;

  [s1,1,2,1,true] call ACE_fnc_PackIFAK;
  _s1playerweap = [
	 "CZ805_A1_GL_ACR",
	 "ACRE_PRC117F",
	 "ACE_Rangefinder_OD",
	 "ACRE_PRC148_UHF",
	 "ItemCompass",
	 "ACE_DAGR",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ACE_HuntIR_monitor",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	  "ItemWatch"
	 ];

  _s1playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "HandGrenade_West",
	 "SmokeShellBlue",
	 "SmokeShellBlue",
	 "ACE_Battery_Rangefinder",
	 "30Rnd_556x45_G36",
	 "ACE_HuntIR_M203",
	 "ACE_HuntIR_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_SmokeRed_M203",
	 "1Rnd_SmokeRed_M203",
	 "1Rnd_HE_M203",
	  "1Rnd_HE_M203"
	 ];

  _s1playerweapback = "";

  _s1playerweapruck = [["ACRE_PRC343",1]];
  _s1playerammoruck = [["30Rnd_556x45_G36",3],["30Rnd_556x45_G36",2],["SmokeShellBlue",2]];
  s1 setvariable ["ACE_RuckWepContents", _s1playerweapruck];
  s1 setvariable ["ACE_RuckMagContents", _s1playerammoruck];
  s1 setvariable ["ACE_weapononback", _s1playerweapback];
  {s1 addmagazine _x} foreach _s1playerammo;
  {s1 addWeapon _x} foreach _s1playerweap;

  s1 selectWeapon (primaryWeapon s1);

  removeallweapons s2;
  removeallitems s2;
  removeBackpack s2;

  [s2,2,2,2,true] call ACE_fnc_PackIFAK;
  _s2playerweap = [
	 "CZ805_A2_ACR",
	 "ACE_Rucksack_MOLLE_Green_Medic",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_Earplugs",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s2playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "ACE_Medkit",
	  "ACE_Medkit"
	 ];

  _s2playerweapback = "";

  _s2playerweapruck = [];
  _s2playerammoruck = [["ACE_LargeBandage",10],["ACE_Bandage",15],["ACE_Epinephrine",15],["ACE_Morphine",15],["SmokeShellGreen",2],["ACE_Medkit",10]];
  s2 setvariable ["ACE_RuckMagContents", _s2playerammoruck];
  s2 setvariable ["ACE_weapononback", _s2playerweapback];
  {s2 addmagazine _x} foreach _s2playerammo;
  {s2 addWeapon _x} foreach _s2playerweap;

  s2 selectWeapon (primaryWeapon s2);

  removeallweapons s3;
  removeallitems s3;
  removeBackpack s3;

  [s3,1,2,1,true] call ACE_fnc_PackIFAK;
  _s3playerweap = [
	 "CZ805_A1_GL_ACR",
	 "M136",
	 "Binocular",
	 "ACRE_PRC148_UHF",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ACE_HuntIR_monitor",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s3playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "SmokeShellBlue",
	 "SmokeShellBlue",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	  "1Rnd_HE_M203"
	 ];

  _s3playerweapback = "";

  _s3playerweapruck = [];
  _s3playerammoruck = [];
  s3 setvariable ["ACE_weapononback", _s3playerweapback];
  {s3 addmagazine _x} foreach _s3playerammo;
  {s3 addWeapon _x} foreach _s3playerweap;

  s3 selectWeapon (primaryWeapon s3);

  removeallweapons s4;
  removeallitems s4;
  removeBackpack s4;

  [s4,1,2,1,true] call ACE_fnc_PackIFAK;
  _s4playerweap = [
	 "CZ805_A2_ACR",
	 "ACE_BackPack",
	 "ACE_P226",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_Earplugs",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s4playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "SmokeShellBlue",
	 "SmokeShellBlue",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	  "ACE_15Rnd_9x19_P226"
	 ];

  _s4playerweapback = "";

  _s4playerweapruck = [];
  _s4playerammoruck = [["PipeBomb",1],["HandGrenade_West",2],["ACE_C4_M",4]];
  s4 setvariable ["ACE_RuckMagContents", _s4playerammoruck];
  s4 setvariable ["ACE_weapononback", _s4playerweapback];
  {s4 addmagazine _x} foreach _s4playerammo;
  {s4 addWeapon _x} foreach _s4playerweap;

  s4 selectWeapon (primaryWeapon s4);

  removeallweapons s5;
  removeallitems s5;
  removeBackpack s5;

  [s5,1,2,1,true] call ACE_fnc_PackIFAK;
  _s5playerweap = [
	 "UK59_ACR",
	 "ACE_Stretcher",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	  "ItemWatch"
	 ];

  _s5playerammo = [
	 "100Rnd_762x54_PK",
	 "100Rnd_762x54_PK",
	 "100Rnd_762x54_PK",
	 "100Rnd_762x54_PK",
	 "100Rnd_762x54_PK",
	  "100Rnd_762x54_PK"
	 ];

  _s5playerweapback = "";

  _s5playerweapruck = [];
  _s5playerammoruck = [];
  s5 setvariable ["ACE_weapononback", _s5playerweapback];
  {s5 addmagazine _x} foreach _s5playerammo;
  {s5 addWeapon _x} foreach _s5playerweap;

  s5 selectWeapon (primaryWeapon s5);

  removeallweapons s6;
  removeallitems s6;
  removeBackpack s6;

  [s6,1,2,1,true] call ACE_fnc_PackIFAK;
  _s6playerweap = [
	 "CZ805_A2_ACR",
	 "ACE_Rucksack_MOLLE_Green",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	  "ItemWatch"
	 ];

  _s6playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "SmokeShellBlue",
	  "SmokeShellBlue"
	 ];

  _s6playerweapback = "";

  _s6playerweapruck = [];
  _s6playerammoruck = [["100Rnd_762x54_PK",3],["100Rnd_762x54_PK",2],["HandGrenade_West",2]];
  s6 setvariable ["ACE_RuckMagContents", _s6playerammoruck];
  s6 setvariable ["ACE_weapononback", _s6playerweapback];
  {s6 addmagazine _x} foreach _s6playerammo;
  {s6 addWeapon _x} foreach _s6playerweap;

  s6 selectWeapon (primaryWeapon s6);

  removeallweapons s7;
  removeallitems s7;
  removeBackpack s7;

  [s7,1,2,1,true] call ACE_fnc_PackIFAK;
  _s7playerweap = [
	 "CZ805_A2_ACR",
	 "M136",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	  "ItemWatch"
	 ];

  _s7playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	  "SmokeShellBlue"
	 ];

  _s7playerweapback = "ACE_Rucksack_MOLLE_Green";

  _s7playerweapruck = [];
  _s7playerammoruck = [["30Rnd_556x45_G36",8],["SmokeShellBlue",2],["HandGrenade_West",2]];
  s7 setvariable ["ACE_RuckMagContents", _s7playerammoruck];
  s7 setvariable ["ACE_weapononback", _s7playerweapback];
  {s7 addmagazine _x} foreach _s7playerammo;
  {s7 addWeapon _x} foreach _s7playerweap;

  s7 selectWeapon (primaryWeapon s7);

  removeallweapons s8;
  removeallitems s8;
  removeBackpack s8;

  [s8,1,2,1,true] call ACE_fnc_PackIFAK;
  _s8playerweap = [
	 "CZ805_A1_ACR",
	 "ACE_Rucksack_MOLLE_Green",
	 "ACE_P226",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	  "ItemWatch"
	 ];

  _s8playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "SmokeShellBlue",
	 "SmokeShellBlue",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	  "ACE_15Rnd_9x19_P226"
	 ];

  _s8playerweapback = "";

  _s8playerweapruck = [];
  _s8playerammoruck = [["30Rnd_556x45_G36",6],["HandGrenade_West",2]];
  s8 setvariable ["ACE_RuckMagContents", _s8playerammoruck];
  s8 setvariable ["ACE_weapononback", _s8playerweapback];
  {s8 addmagazine _x} foreach _s8playerammo;
  {s8 addWeapon _x} foreach _s8playerweap;

  s8 selectWeapon (primaryWeapon s8);

  removeallweapons s9;
  removeallitems s9;
  removeBackpack s9;

  [s9,1,2,1,true] call ACE_fnc_PackIFAK;
  _s9playerweap = [
	 "CZ805_A1_GL_ACR",
	 "M136",
	 "Binocular",
	 "ACRE_PRC148_UHF",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ACE_HuntIR_monitor",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s9playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "SmokeShellBlue",
	 "SmokeShellBlue",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	  "1Rnd_HE_M203"
	 ];

  _s9playerweapback = "";

  _s9playerweapruck = [];
  _s9playerammoruck = [];
  s9 setvariable ["ACE_weapononback", _s9playerweapback];
  {s9 addmagazine _x} foreach _s9playerammo;
  {s9 addWeapon _x} foreach _s9playerweap;

  s9 selectWeapon (primaryWeapon s9);

  removeallweapons s10;
  removeallitems s10;
  removeBackpack s10;

  [s10,1,2,1,true] call ACE_fnc_PackIFAK;
  _s10playerweap = [
	 "CZ805_A1_ACR",
	 "ACE_Rucksack_MOLLE_Green",
	 "ACE_P226",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	  "ItemWatch"
	 ];

  _s10playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "SmokeShellBlue",
	 "SmokeShellBlue",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	  "ACE_15Rnd_9x19_P226"
	 ];

  _s10playerweapback = "";

  _s10playerweapruck = [];
  _s10playerammoruck = [["30Rnd_556x45_G36",6],["HandGrenade_West",2]];
  s10 setvariable ["ACE_RuckMagContents", _s10playerammoruck];
  s10 setvariable ["ACE_weapononback", _s10playerweapback];
  {s10 addmagazine _x} foreach _s10playerammo;
  {s10 addWeapon _x} foreach _s10playerweap;

  s10 selectWeapon (primaryWeapon s10);

  removeallweapons s11;
  removeallitems s11;
  removeBackpack s11;

  [s11,1,2,1,true] call ACE_fnc_PackIFAK;
  _s11playerweap = [
	 "CZ805_A2_ACR",
	 "MAAWS",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_Earplugs",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s11playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "MAAWS_HEAT",
	  "MAAWS_HEAT"
	 ];

  _s11playerweapback = "";

  _s11playerweapruck = [];
  _s11playerammoruck = [];
  s11 setvariable ["ACE_weapononback", _s11playerweapback];
  {s11 addmagazine _x} foreach _s11playerammo;
  {s11 addWeapon _x} foreach _s11playerweap;

  s11 selectWeapon (primaryWeapon s11);

  removeallweapons s12;
  removeallitems s12;
  removeBackpack s12;

  [s12,1,2,1,true] call ACE_fnc_PackIFAK;
  _s12playerweap = [
	 "CZ805_A2_ACR",
	 "ACE_VTAC_RUSH72",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_Earplugs",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s12playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "SmokeShellGreen",
	  "SmokeShellGreen"
	 ];

  _s12playerweapback = "";

  _s12playerweapruck = [];
  _s12playerammoruck = [["MAAWS_HEAT",2],["MAAWS_HEDP",2]];
  s12 setvariable ["ACE_RuckMagContents", _s12playerammoruck];
  s12 setvariable ["ACE_weapononback", _s12playerweapback];
  {s12 addmagazine _x} foreach _s12playerammo;
  {s12 addWeapon _x} foreach _s12playerweap;

  s12 selectWeapon (primaryWeapon s12);

  removeallweapons s13;
  removeallitems s13;
  removeBackpack s13;

  [s13,1,2,1,true] call ACE_fnc_PackIFAK;
  _s13playerweap = [
	 "ACE_M27_IAR",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	  "ItemWatch"
	 ];

  _s13playerammo = [
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "SmokeShellBlue",
	  "SmokeShellBlue"
	 ];

  _s13playerweapback = "ACE_WireCutter";

  _s13playerweapruck = [];
  _s13playerammoruck = [];
  s13 setvariable ["ACE_weapononback", _s13playerweapback];
  {s13 addmagazine _x} foreach _s13playerammo;
  {s13 addWeapon _x} foreach _s13playerweap;

  s13 selectWeapon (primaryWeapon s13);

  removeallweapons s14;
  removeallitems s14;
  removeBackpack s14;

  [s14,1,2,1,true] call ACE_fnc_PackIFAK;
  _s14playerweap = [
	 "CZ805_A1_GL_ACR",
	 "ACE_Rucksack_MOLLE_Green",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	  "ItemWatch"
	 ];

  _s14playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "SmokeShellBlue",
	 "SmokeShellBlue",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "ACE_40mm_Buck_M79",
	  "ACE_40mm_Buck_M79"
	 ];

  _s14playerweapback = "";

  _s14playerweapruck = [];
  _s14playerammoruck = [["30Rnd_556x45_G36",8],["1Rnd_HE_M203",2]];
  s14 setvariable ["ACE_RuckMagContents", _s14playerammoruck];
  s14 setvariable ["ACE_weapononback", _s14playerweapback];
  {s14 addmagazine _x} foreach _s14playerammo;
  {s14 addWeapon _x} foreach _s14playerweap;

  s14 selectWeapon (primaryWeapon s14);

  removeallweapons s1_1;
  removeallitems s1_1;
  removeBackpack s1_1;

  [s1_1,1,2,1,true] call ACE_fnc_PackIFAK;
  _s1_1playerweap = [
	 "CZ805_A1_GL_ACR",
	 "ACRE_PRC117F",
	 "ACE_Rangefinder_OD",
	 "ACRE_PRC148_UHF",
	 "ItemCompass",
	 "ACE_DAGR",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ACE_HuntIR_monitor",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	  "ItemWatch"
	 ];

  _s1_1playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "HandGrenade_West",
	 "SmokeShellBlue",
	 "SmokeShellBlue",
	 "ACE_Battery_Rangefinder",
	 "30Rnd_556x45_G36",
	 "ACE_HuntIR_M203",
	 "ACE_HuntIR_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_SmokeRed_M203",
	 "1Rnd_SmokeRed_M203",
	 "1Rnd_HE_M203",
	  "1Rnd_HE_M203"
	 ];

  _s1_1playerweapback = "";

  _s1_1playerweapruck = [["ACRE_PRC343",1]];
  _s1_1playerammoruck = [["30Rnd_556x45_G36",3],["30Rnd_556x45_G36",2],["SmokeShellBlue",2]];
  s1_1 setvariable ["ACE_RuckWepContents", _s1_1playerweapruck];
  s1_1 setvariable ["ACE_RuckMagContents", _s1_1playerammoruck];
  s1_1 setvariable ["ACE_weapononback", _s1_1playerweapback];
  {s1_1 addmagazine _x} foreach _s1_1playerammo;
  {s1_1 addWeapon _x} foreach _s1_1playerweap;

  s1_1 selectWeapon (primaryWeapon s1_1);

  removeallweapons s2_1;
  removeallitems s2_1;
  removeBackpack s2_1;

  [s2_1,2,2,2,true] call ACE_fnc_PackIFAK;
  _s2_1playerweap = [
	 "CZ805_A2_ACR",
	 "ACE_Rucksack_MOLLE_Green_Medic",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_Earplugs",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s2_1playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "ACE_Medkit",
	  "ACE_Medkit"
	 ];

  _s2_1playerweapback = "";

  _s2_1playerweapruck = [];
  _s2_1playerammoruck = [["ACE_LargeBandage",10],["ACE_Bandage",15],["ACE_Epinephrine",15],["ACE_Morphine",15],["SmokeShellGreen",2],["ACE_Medkit",10]];
  s2_1 setvariable ["ACE_RuckMagContents", _s2_1playerammoruck];
  s2_1 setvariable ["ACE_weapononback", _s2_1playerweapback];
  {s2_1 addmagazine _x} foreach _s2_1playerammo;
  {s2_1 addWeapon _x} foreach _s2_1playerweap;

  s2_1 selectWeapon (primaryWeapon s2_1);

  removeallweapons s3_1;
  removeallitems s3_1;
  removeBackpack s3_1;

  [s3_1,1,2,1,true] call ACE_fnc_PackIFAK;
  _s3_1playerweap = [
	 "CZ805_A1_GL_ACR",
	 "M136",
	 "Binocular",
	 "ACRE_PRC148_UHF",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ACE_HuntIR_monitor",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s3_1playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "SmokeShellBlue",
	 "SmokeShellBlue",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	  "1Rnd_HE_M203"
	 ];

  _s3_1playerweapback = "";

  _s3_1playerweapruck = [];
  _s3_1playerammoruck = [];
  s3_1 setvariable ["ACE_weapononback", _s3_1playerweapback];
  {s3_1 addmagazine _x} foreach _s3_1playerammo;
  {s3_1 addWeapon _x} foreach _s3_1playerweap;

  s3_1 selectWeapon (primaryWeapon s3_1);

  removeallweapons s4_1;
  removeallitems s4_1;
  removeBackpack s4_1;

  [s4_1,1,2,1,true] call ACE_fnc_PackIFAK;
  _s4_1playerweap = [
	 "CZ805_A2_ACR",
	 "ACE_BackPack",
	 "ACE_P226",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_Earplugs",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s4_1playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "SmokeShellBlue",
	 "SmokeShellBlue",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	  "ACE_15Rnd_9x19_P226"
	 ];

  _s4_1playerweapback = "";

  _s4_1playerweapruck = [];
  _s4_1playerammoruck = [["PipeBomb",1],["HandGrenade_West",2],["ACE_C4_M",4]];
  s4_1 setvariable ["ACE_RuckMagContents", _s4_1playerammoruck];
  s4_1 setvariable ["ACE_weapononback", _s4_1playerweapback];
  {s4_1 addmagazine _x} foreach _s4_1playerammo;
  {s4_1 addWeapon _x} foreach _s4_1playerweap;

  s4_1 selectWeapon (primaryWeapon s4_1);

  removeallweapons s5_1;
  removeallitems s5_1;
  removeBackpack s5_1;

  [s5_1,1,2,1,true] call ACE_fnc_PackIFAK;
  _s5_1playerweap = [
	 "UK59_ACR",
	 "ACE_Stretcher",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	  "ItemWatch"
	 ];

  _s5_1playerammo = [
	 "100Rnd_762x54_PK",
	 "100Rnd_762x54_PK",
	 "100Rnd_762x54_PK",
	 "100Rnd_762x54_PK",
	 "100Rnd_762x54_PK",
	  "100Rnd_762x54_PK"
	 ];

  _s5_1playerweapback = "";

  _s5_1playerweapruck = [];
  _s5_1playerammoruck = [];
  s5_1 setvariable ["ACE_weapononback", _s5_1playerweapback];
  {s5_1 addmagazine _x} foreach _s5_1playerammo;
  {s5_1 addWeapon _x} foreach _s5_1playerweap;

  s5_1 selectWeapon (primaryWeapon s5_1);

  removeallweapons s6_1;
  removeallitems s6_1;
  removeBackpack s6_1;

  [s6_1,1,2,1,true] call ACE_fnc_PackIFAK;
  _s6_1playerweap = [
	 "CZ805_A2_ACR",
	 "ACE_Rucksack_MOLLE_Green",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	  "ItemWatch"
	 ];

  _s6_1playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "SmokeShellBlue",
	  "SmokeShellBlue"
	 ];

  _s6_1playerweapback = "";

  _s6_1playerweapruck = [];
  _s6_1playerammoruck = [["100Rnd_762x54_PK",3],["100Rnd_762x54_PK",2],["HandGrenade_West",2]];
  s6_1 setvariable ["ACE_RuckMagContents", _s6_1playerammoruck];
  s6_1 setvariable ["ACE_weapononback", _s6_1playerweapback];
  {s6_1 addmagazine _x} foreach _s6_1playerammo;
  {s6_1 addWeapon _x} foreach _s6_1playerweap;

  s6_1 selectWeapon (primaryWeapon s6_1);

  removeallweapons s7_1;
  removeallitems s7_1;
  removeBackpack s7_1;

  [s7_1,1,2,1,true] call ACE_fnc_PackIFAK;
  _s7_1playerweap = [
	 "CZ805_A2_ACR",
	 "M136",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	  "ItemWatch"
	 ];

  _s7_1playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	  "SmokeShellBlue"
	 ];

  _s7_1playerweapback = "ACE_Rucksack_MOLLE_Green";

  _s7_1playerweapruck = [];
  _s7_1playerammoruck = [["30Rnd_556x45_G36",8],["SmokeShellBlue",2],["HandGrenade_West",2]];
  s7_1 setvariable ["ACE_RuckMagContents", _s7_1playerammoruck];
  s7_1 setvariable ["ACE_weapononback", _s7_1playerweapback];
  {s7_1 addmagazine _x} foreach _s7_1playerammo;
  {s7_1 addWeapon _x} foreach _s7_1playerweap;

  s7_1 selectWeapon (primaryWeapon s7_1);

  removeallweapons s8_1;
  removeallitems s8_1;
  removeBackpack s8_1;

  [s8_1,1,2,1,true] call ACE_fnc_PackIFAK;
  _s8_1playerweap = [
	 "CZ805_A1_ACR",
	 "ACE_Rucksack_MOLLE_Green",
	 "ACE_P226",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	  "ItemWatch"
	 ];

  _s8_1playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "SmokeShellBlue",
	 "SmokeShellBlue",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	  "ACE_15Rnd_9x19_P226"
	 ];

  _s8_1playerweapback = "";

  _s8_1playerweapruck = [];
  _s8_1playerammoruck = [["30Rnd_556x45_G36",6],["HandGrenade_West",2]];
  s8_1 setvariable ["ACE_RuckMagContents", _s8_1playerammoruck];
  s8_1 setvariable ["ACE_weapononback", _s8_1playerweapback];
  {s8_1 addmagazine _x} foreach _s8_1playerammo;
  {s8_1 addWeapon _x} foreach _s8_1playerweap;

  s8_1 selectWeapon (primaryWeapon s8_1);

  removeallweapons s9_1;
  removeallitems s9_1;
  removeBackpack s9_1;

  [s9_1,1,2,1,true] call ACE_fnc_PackIFAK;
  _s9_1playerweap = [
	 "CZ805_A1_GL_ACR",
	 "M136",
	 "Binocular",
	 "ACRE_PRC148_UHF",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_Earplugs",
	 "ItemGPS",
	 "ACE_HuntIR_monitor",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s9_1playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "SmokeShellBlue",
	 "SmokeShellBlue",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	  "1Rnd_HE_M203"
	 ];

  _s9_1playerweapback = "";

  _s9_1playerweapruck = [];
  _s9_1playerammoruck = [];
  s9_1 setvariable ["ACE_weapononback", _s9_1playerweapback];
  {s9_1 addmagazine _x} foreach _s9_1playerammo;
  {s9_1 addWeapon _x} foreach _s9_1playerweap;

  s9_1 selectWeapon (primaryWeapon s9_1);

  removeallweapons s10_1;
  removeallitems s10_1;
  removeBackpack s10_1;

  [s10_1,1,2,1,true] call ACE_fnc_PackIFAK;
  _s10_1playerweap = [
	 "CZ805_A1_ACR",
	 "ACE_Rucksack_MOLLE_Green",
	 "ACE_P226",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	  "ItemWatch"
	 ];

  _s10_1playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "SmokeShellBlue",
	 "SmokeShellBlue",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	 "ACE_15Rnd_9x19_P226",
	  "ACE_15Rnd_9x19_P226"
	 ];

  _s10_1playerweapback = "";

  _s10_1playerweapruck = [];
  _s10_1playerammoruck = [["30Rnd_556x45_G36",6],["HandGrenade_West",2]];
  s10_1 setvariable ["ACE_RuckMagContents", _s10_1playerammoruck];
  s10_1 setvariable ["ACE_weapononback", _s10_1playerweapback];
  {s10_1 addmagazine _x} foreach _s10_1playerammo;
  {s10_1 addWeapon _x} foreach _s10_1playerweap;

  s10_1 selectWeapon (primaryWeapon s10_1);

  removeallweapons s11_1;
  removeallitems s11_1;
  removeBackpack s11_1;

  [s11_1,1,2,1,true] call ACE_fnc_PackIFAK;
  _s11_1playerweap = [
	 "CZ805_A2_ACR",
	 "MAAWS",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_Earplugs",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s11_1playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "MAAWS_HEAT",
	  "MAAWS_HEAT"
	 ];

  _s11_1playerweapback = "";

  _s11_1playerweapruck = [];
  _s11_1playerammoruck = [];
  s11_1 setvariable ["ACE_weapononback", _s11_1playerweapback];
  {s11_1 addmagazine _x} foreach _s11_1playerammo;
  {s11_1 addWeapon _x} foreach _s11_1playerweap;

  s11_1 selectWeapon (primaryWeapon s11_1);

  removeallweapons s12_1;
  removeallitems s12_1;
  removeBackpack s12_1;

  [s12_1,1,2,1,true] call ACE_fnc_PackIFAK;
  _s12_1playerweap = [
	 "CZ805_A2_ACR",
	 "ACE_VTAC_RUSH72",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_Earplugs",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s12_1playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "SmokeShellGreen",
	  "SmokeShellGreen"
	 ];

  _s12_1playerweapback = "";

  _s12_1playerweapruck = [];
  _s12_1playerammoruck = [["MAAWS_HEAT",2],["MAAWS_HEDP",2]];
  s12_1 setvariable ["ACE_RuckMagContents", _s12_1playerammoruck];
  s12_1 setvariable ["ACE_weapononback", _s12_1playerweapback];
  {s12_1 addmagazine _x} foreach _s12_1playerammo;
  {s12_1 addWeapon _x} foreach _s12_1playerweap;

  s12_1 selectWeapon (primaryWeapon s12_1);

  removeallweapons s13_1;
  removeallitems s13_1;
  removeBackpack s13_1;

  [s13_1,1,2,1,true] call ACE_fnc_PackIFAK;
  _s13_1playerweap = [
	 "ACE_M27_IAR",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	  "ItemWatch"
	 ];

  _s13_1playerammo = [
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "SmokeShellBlue",
	  "SmokeShellBlue"
	 ];

  _s13_1playerweapback = "ACE_WireCutter";

  _s13_1playerweapruck = [];
  _s13_1playerammoruck = [];
  s13_1 setvariable ["ACE_weapononback", _s13_1playerweapback];
  {s13_1 addmagazine _x} foreach _s13_1playerammo;
  {s13_1 addWeapon _x} foreach _s13_1playerweap;

  s13_1 selectWeapon (primaryWeapon s13_1);

  removeallweapons s14_1;
  removeallitems s14_1;
  removeBackpack s14_1;

  [s14_1,1,2,1,true] call ACE_fnc_PackIFAK;
  _s14_1playerweap = [
	 "CZ805_A1_GL_ACR",
	 "ACE_Rucksack_MOLLE_Green",
	 "ACRE_PRC343",
	 "ACE_GlassesBalaklava",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ItemMap",
	 "ACE_GlassesLHD_glasses",
	  "ItemWatch"
	 ];

  _s14_1playerammo = [
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "30Rnd_556x45_G36",
	 "SmokeShellBlue",
	 "SmokeShellBlue",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "ACE_40mm_Buck_M79",
	  "ACE_40mm_Buck_M79"
	 ];

  _s14_1playerweapback = "";

  _s14_1playerweapruck = [];
  _s14_1playerammoruck = [["30Rnd_556x45_G36",8],["1Rnd_HE_M203",2]];
  s14_1 setvariable ["ACE_RuckMagContents", _s14_1playerammoruck];
  s14_1 setvariable ["ACE_weapononback", _s14_1playerweapback];
  {s14_1 addmagazine _x} foreach _s14_1playerammo;
  {s14_1 addWeapon _x} foreach _s14_1playerweap;

  s14_1 selectWeapon (primaryWeapon s14_1);