// DO NOT EDIT THIS FILE
enableSaving [false,false];
setGroupIconsVisible [true,false]; //Show only 2D
enableCamShake true;
setViewDistance 800;
setTerrainGrid 25;

// clients
if (!isDedicated) then {

	[] spawn {
		waitUntil {!isNull player};
		// deletes grenades thrown in spawn
		player addEventHandler ["Fired",
		{
			if (_this select 2 == "HandGrenadeMuzzle") then
			{
				if ((_this select 0) distance (markerPos (["respawn_west","respawn_east","respawn_guerrila","respawn_civilian"] select ([WEST,EAST,independent,civilian] find side player))) < 50) then
				{
					deleteVehicle (_this select 6);
					titleText ["G IS FOR GRENADES", "PLAIN", 3];
				};
			};
		}];
		sleep  0.3;
		// lower weapon
		player switchMove "amovpercmstpslowwrfldnon";

		// player never joins "ENEMY" side after killing too many civs
		while {true} do {
			waitUntil {sleep 2; alive player};
			if (rating player < 0) then {
				player addRating (abs(rating player));
			};
		};
	};
};

// server
if (isServer) then
{
	createCenter west;
	createCenter east;
	createCenter resistance;
	createCenter civilian;
};
