/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.3.57
* Tue Jun 19 18:14:36 CEST 2012
* Mission file name: co27_opoyster.Takistan
* Mission name: co27_opoyster.Takistan
* Required mods:
* + ACE
* + ACRE
* 
* Call the script: _dummy = [] execvm "lea\loadout-solo.sqf";
* 
*/

/**
* Loadout for vehicles
*/

//No named vehicles in this mission.

/**
* Loadout for ai units
*/

//No named AI units in this mission.

/**
* Loadout for playable units
*/


  removeallweapons s1;
  removeallitems s1;
  removeBackpack s1;

  _s1playerweap = [
	 "ACE_HK416_D14_COMPM3_M320",
	 "M136",
	 "ACE_USP",
	 "Binocular_Vector",
	 "ACRE_PRC148_UHF",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ACE_HuntIR_monitor",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s1playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "SmokeShellOrange",
	 "ACE_Battery_Rangefinder",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "ACE_HuntIR_M203",
	 "ACE_HuntIR_M203",
	 "ACE_12Rnd_45ACP_USP",
	 "ACE_12Rnd_45ACP_USP",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	  "1Rnd_Smoke_M203"
	 ];

  _s1playerweapback = "";

  _s1playerweapruck = [];
  _s1playerammoruck = [];
  s1 setvariable ["ACE_weapononback", _s1playerweapback];
  {s1 addmagazine _x} foreach _s1playerammo;
  {s1 addWeapon _x} foreach _s1playerweap;

  s1 selectWeapon (primaryWeapon s1);

  removeallweapons s2;
  removeallitems s2;
  removeBackpack s2;

  _s2playerweap = [
	 "ACE_HK416_D10_Holo",
	 "ACE_CharliePack_ACU_Medic",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s2playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s2playerweapback = "";

  _s2playerweapruck = [];
  _s2playerammoruck = [["ACE_LargeBandage",12],["ACE_Bandage",15],["ACE_Medkit",8],["ACE_Epinephrine",15],["ACE_Morphine",15]];
  s2 setvariable ["ACE_RuckMagContents", _s2playerammoruck];
  s2 setvariable ["ACE_weapononback", _s2playerweapback];
  {s2 addmagazine _x} foreach _s2playerammo;
  {s2 addWeapon _x} foreach _s2playerweap;

  s2 selectWeapon (primaryWeapon s2);

  removeallweapons s3;
  removeallitems s3;
  removeBackpack s3;

  _s3playerweap = [
	 "ACE_HK416_D14_COMPM3_M320",
	 "ACE_BackPack",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s3playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "ACE_12Rnd_45ACP_USP",
	 "ACE_12Rnd_45ACP_USP",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	  "1Rnd_HE_M203"
	 ];

  _s3playerweapback = "M136";

  _s3playerweapruck = [];
  _s3playerammoruck = [["30Rnd_556x45_Stanag",4],["1Rnd_HE_M203",2]];
  s3 setvariable ["ACE_RuckMagContents", _s3playerammoruck];
  s3 setvariable ["ACE_weapononback", _s3playerweapback];
  {s3 addmagazine _x} foreach _s3playerammo;
  {s3 addWeapon _x} foreach _s3playerweap;

  s3 selectWeapon (primaryWeapon s3);

  removeallweapons s4;
  removeallitems s4;
  removeBackpack s4;

  _s4playerweap = [
	 "ACE_HK416_D10_Holo",
	 "ACE_VTAC_RUSH72",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s4playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s4playerweapback = "";

  _s4playerweapruck = [];
  _s4playerammoruck = [["PipeBomb",1],["ACE_C4_M",4],["30Rnd_556x45_Stanag",2]];
  s4 setvariable ["ACE_RuckMagContents", _s4playerammoruck];
  s4 setvariable ["ACE_weapononback", _s4playerweapback];
  {s4 addmagazine _x} foreach _s4playerammo;
  {s4 addWeapon _x} foreach _s4playerweap;

  s4 selectWeapon (primaryWeapon s4);

  removeallweapons s5;
  removeallitems s5;
  removeBackpack s5;

  _s5playerweap = [
	 "M249_EP1",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s5playerammo = [
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "ACE_200Rnd_556x45_T_M249",
	 "ACE_200Rnd_556x45_T_M249",
	 "ACE_200Rnd_556x45_T_M249",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s5playerweapback = "";

  _s5playerweapruck = [];
  _s5playerammoruck = [];
  s5 setvariable ["ACE_weapononback", _s5playerweapback];
  {s5 addmagazine _x} foreach _s5playerammo;
  {s5 addWeapon _x} foreach _s5playerweap;

  s5 selectWeapon (primaryWeapon s5);

  removeallweapons s6;
  removeallitems s6;
  removeBackpack s6;

  _s6playerweap = [
	 "ACE_HK416_D10_Holo",
	 "ACE_Backpack_US",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s6playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s6playerweapback = "";

  _s6playerweapruck = [];
  _s6playerammoruck = [["ACE_200Rnd_556x45_T_M249",3],["30Rnd_556x45_Stanag",3]];
  s6 setvariable ["ACE_RuckMagContents", _s6playerammoruck];
  s6 setvariable ["ACE_weapononback", _s6playerweapback];
  {s6 addmagazine _x} foreach _s6playerammo;
  {s6 addWeapon _x} foreach _s6playerweap;

  s6 selectWeapon (primaryWeapon s6);

  removeallweapons s7;
  removeallitems s7;
  removeBackpack s7;

  _s7playerweap = [
	 "ACE_HK416_D14_COMPM3_M320",
	 "M136",
	 "ACE_USP",
	 "Binocular_Vector",
	 "ACRE_PRC148_UHF",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ACE_HuntIR_monitor",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s7playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "SmokeShellOrange",
	 "ACE_Battery_Rangefinder",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "ACE_HuntIR_M203",
	 "ACE_HuntIR_M203",
	 "ACE_12Rnd_45ACP_USP",
	 "ACE_12Rnd_45ACP_USP",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	  "1Rnd_Smoke_M203"
	 ];

  _s7playerweapback = "";

  _s7playerweapruck = [];
  _s7playerammoruck = [];
  s7 setvariable ["ACE_weapononback", _s7playerweapback];
  {s7 addmagazine _x} foreach _s7playerammo;
  {s7 addWeapon _x} foreach _s7playerweap;

  s7 selectWeapon (primaryWeapon s7);

  removeallweapons s8;
  removeallitems s8;
  removeBackpack s8;

  _s8playerweap = [
	 "ACE_HK416_D10_Holo",
	 "ACE_CharliePack_ACU_Medic",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s8playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s8playerweapback = "";

  _s8playerweapruck = [];
  _s8playerammoruck = [["ACE_LargeBandage",12],["ACE_Bandage",15],["ACE_Medkit",8],["ACE_Epinephrine",15],["ACE_Morphine",15]];
  s8 setvariable ["ACE_RuckMagContents", _s8playerammoruck];
  s8 setvariable ["ACE_weapononback", _s8playerweapback];
  {s8 addmagazine _x} foreach _s8playerammo;
  {s8 addWeapon _x} foreach _s8playerweap;

  s8 selectWeapon (primaryWeapon s8);

  removeallweapons s9;
  removeallitems s9;
  removeBackpack s9;

  _s9playerweap = [
	 "ACE_M4_ACOG",
	 "ACE_BackPack",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s9playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s9playerweapback = "M136";

  _s9playerweapruck = [];
  _s9playerammoruck = [["30Rnd_556x45_Stanag",6]];
  s9 setvariable ["ACE_RuckMagContents", _s9playerammoruck];
  s9 setvariable ["ACE_weapononback", _s9playerweapback];
  {s9 addmagazine _x} foreach _s9playerammo;
  {s9 addWeapon _x} foreach _s9playerweap;

  s9 selectWeapon (primaryWeapon s9);

  removeallweapons s10;
  removeallitems s10;
  removeBackpack s10;

  _s10playerweap = [
	 "ACE_HK416_D10",
	 "M136",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s10playerammo = [
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "100Rnd_556x45_BetaCMag",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s10playerweapback = "";

  _s10playerweapruck = [];
  _s10playerammoruck = [];
  s10 setvariable ["ACE_weapononback", _s10playerweapback];
  {s10 addmagazine _x} foreach _s10playerammo;
  {s10 addWeapon _x} foreach _s10playerweap;

  s10 selectWeapon (primaryWeapon s10);

  removeallweapons s11;
  removeallitems s11;
  removeBackpack s11;

  _s11playerweap = [
	 "ACE_HK416_D10_Holo",
	 "MAAWS",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s11playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "MAAWS_HEAT",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s11playerweapback = "";

  _s11playerweapruck = [];
  _s11playerammoruck = [];
  s11 setvariable ["ACE_weapononback", _s11playerweapback];
  {s11 addmagazine _x} foreach _s11playerammo;
  {s11 addWeapon _x} foreach _s11playerweap;

  s11 selectWeapon (primaryWeapon s11);

  removeallweapons s12;
  removeallitems s12;
  removeBackpack s12;

  _s12playerweap = [
	 "ACE_HK416_D10_Holo",
	 "ACE_Rucksack_MOLLE_DMARPAT",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s12playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s12playerweapback = "";

  _s12playerweapruck = [];
  _s12playerammoruck = [["MAAWS_HEAT",2],["MAAWS_HEDP",2]];
  s12 setvariable ["ACE_RuckMagContents", _s12playerammoruck];
  s12 setvariable ["ACE_weapononback", _s12playerweapback];
  {s12 addmagazine _x} foreach _s12playerammo;
  {s12 addWeapon _x} foreach _s12playerweap;

  s12 selectWeapon (primaryWeapon s12);

  removeallweapons s13;
  removeallitems s13;
  removeBackpack s13;

  _s13playerweap = [
	 "ACE_HK416_D14_COMPM3_M320",
	 "M136",
	 "ACE_USP",
	 "Binocular_Vector",
	 "ACRE_PRC148_UHF",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ACE_HuntIR_monitor",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s13playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "SmokeShellOrange",
	 "ACE_Battery_Rangefinder",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "ACE_HuntIR_M203",
	 "ACE_HuntIR_M203",
	 "ACE_12Rnd_45ACP_USP",
	 "ACE_12Rnd_45ACP_USP",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	  "1Rnd_Smoke_M203"
	 ];

  _s13playerweapback = "";

  _s13playerweapruck = [];
  _s13playerammoruck = [];
  s13 setvariable ["ACE_weapononback", _s13playerweapback];
  {s13 addmagazine _x} foreach _s13playerammo;
  {s13 addWeapon _x} foreach _s13playerweap;

  s13 selectWeapon (primaryWeapon s13);

  removeallweapons s14;
  removeallitems s14;
  removeBackpack s14;

  _s14playerweap = [
	 "ACE_HK416_D10_Holo",
	 "ACE_CharliePack_ACU_Medic",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s14playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s14playerweapback = "";

  _s14playerweapruck = [];
  _s14playerammoruck = [["ACE_LargeBandage",12],["ACE_Bandage",15],["ACE_Medkit",8],["ACE_Epinephrine",15],["ACE_Morphine",15]];
  s14 setvariable ["ACE_RuckMagContents", _s14playerammoruck];
  s14 setvariable ["ACE_weapononback", _s14playerweapback];
  {s14 addmagazine _x} foreach _s14playerammo;
  {s14 addWeapon _x} foreach _s14playerweap;

  s14 selectWeapon (primaryWeapon s14);

  removeallweapons s15;
  removeallitems s15;
  removeBackpack s15;

  _s15playerweap = [
	 "ACE_HK416_D14_COMPM3_M320",
	 "ACE_BackPack",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s15playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "ACE_12Rnd_45ACP_USP",
	 "ACE_12Rnd_45ACP_USP",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	  "1Rnd_HE_M203"
	 ];

  _s15playerweapback = "M136";

  _s15playerweapruck = [];
  _s15playerammoruck = [["30Rnd_556x45_Stanag",6]];
  s15 setvariable ["ACE_RuckMagContents", _s15playerammoruck];
  s15 setvariable ["ACE_weapononback", _s15playerweapback];
  {s15 addmagazine _x} foreach _s15playerammo;
  {s15 addWeapon _x} foreach _s15playerweap;

  s15 selectWeapon (primaryWeapon s15);

  removeallweapons s16;
  removeallitems s16;
  removeBackpack s16;

  _s16playerweap = [
	 "ACE_HK416_D10_COMPM3",
	 "ACE_VTAC_RUSH72",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s16playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s16playerweapback = "";

  _s16playerweapruck = [];
  _s16playerammoruck = [["PipeBomb",1],["ACE_C4_M",4]];
  s16 setvariable ["ACE_RuckMagContents", _s16playerammoruck];
  s16 setvariable ["ACE_weapononback", _s16playerweapback];
  {s16 addmagazine _x} foreach _s16playerammo;
  {s16 addWeapon _x} foreach _s16playerweap;

  s16 selectWeapon (primaryWeapon s16);

  removeallweapons s17;
  removeallitems s17;
  removeBackpack s17;

  _s17playerweap = [
	 "ACE_M240B",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s17playerammo = [
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "100Rnd_762x51_M240",
	 "100Rnd_762x51_M240",
	 "100Rnd_762x51_M240",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s17playerweapback = "";

  _s17playerweapruck = [];
  _s17playerammoruck = [];
  s17 setvariable ["ACE_weapononback", _s17playerweapback];
  {s17 addmagazine _x} foreach _s17playerammo;
  {s17 addWeapon _x} foreach _s17playerweap;

  s17 selectWeapon (primaryWeapon s17);

  removeallweapons s18;
  removeallitems s18;
  removeBackpack s18;

  _s18playerweap = [
	 "ACE_HK416_D10_Holo",
	 "ACE_Backpack_US",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _s18playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s18playerweapback = "";

  _s18playerweapruck = [];
  _s18playerammoruck = [["100Rnd_762x51_M240",3]];
  s18 setvariable ["ACE_RuckMagContents", _s18playerammoruck];
  s18 setvariable ["ACE_weapononback", _s18playerweapback];
  {s18 addmagazine _x} foreach _s18playerammo;
  {s18 addWeapon _x} foreach _s18playerweap;

  s18 selectWeapon (primaryWeapon s18);

  removeallweapons s19;
  removeallitems s19;
  removeBackpack s19;

  _s19playerweap = [
	 "ACE_HK416_D14_COMPM3_M320",
	 "M136",
	 "ACE_USP",
	 "Binocular_Vector",
	 "ACRE_PRC148_UHF",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ACE_HuntIR_monitor",
	  "ItemWatch"
	 ];

  _s19playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "SmokeShellOrange",
	 "ACE_Battery_Rangefinder",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "ACE_HuntIR_M203",
	 "ACE_HuntIR_M203",
	 "ACE_12Rnd_45ACP_USP",
	 "ACE_12Rnd_45ACP_USP",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	  "1Rnd_Smoke_M203"
	 ];

  _s19playerweapback = "";

  _s19playerweapruck = [];
  _s19playerammoruck = [];
  s19 setvariable ["ACE_weapononback", _s19playerweapback];
  {s19 addmagazine _x} foreach _s19playerammo;
  {s19 addWeapon _x} foreach _s19playerweap;

  s19 selectWeapon (primaryWeapon s19);

  removeallweapons s20;
  removeallitems s20;
  removeBackpack s20;

  _s20playerweap = [
	 "ACE_HK416_D10_Holo",
	 "ACE_CharliePack_ACU_Medic",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	  "ItemWatch"
	 ];

  _s20playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s20playerweapback = "";

  _s20playerweapruck = [];
  _s20playerammoruck = [["ACE_LargeBandage",12],["ACE_Bandage",15],["ACE_Medkit",8],["ACE_Epinephrine",15],["ACE_Morphine",15]];
  s20 setvariable ["ACE_RuckMagContents", _s20playerammoruck];
  s20 setvariable ["ACE_weapononback", _s20playerweapback];
  {s20 addmagazine _x} foreach _s20playerammo;
  {s20 addWeapon _x} foreach _s20playerweap;

  s20 selectWeapon (primaryWeapon s20);

  removeallweapons s21;
  removeallitems s21;
  removeBackpack s21;

  _s21playerweap = [
	 "ACE_M4_ACOG",
	 "ACE_Rucksack_MOLLE_ACU",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	  "ItemWatch"
	 ];

  _s21playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s21playerweapback = "M136";

  _s21playerweapruck = [];
  _s21playerammoruck = [["30Rnd_556x45_Stanag",6],["SmokeShellGreen",2]];
  s21 setvariable ["ACE_RuckMagContents", _s21playerammoruck];
  s21 setvariable ["ACE_weapononback", _s21playerweapback];
  {s21 addmagazine _x} foreach _s21playerammo;
  {s21 addWeapon _x} foreach _s21playerweap;

  s21 selectWeapon (primaryWeapon s21);

  removeallweapons s23;
  removeallitems s23;
  removeBackpack s23;

  _s23playerweap = [
	 "ACE_HK416_D10_COMPM3",
	 "ACE_VTAC_RUSH72",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	  "ItemWatch"
	 ];

  _s23playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s23playerweapback = "";

  _s23playerweapruck = [];
  _s23playerammoruck = [["PipeBomb",1],["ACE_C4_M",4]];
  s23 setvariable ["ACE_RuckMagContents", _s23playerammoruck];
  s23 setvariable ["ACE_weapononback", _s23playerweapback];
  {s23 addmagazine _x} foreach _s23playerammo;
  {s23 addWeapon _x} foreach _s23playerweap;

  s23 selectWeapon (primaryWeapon s23);

  removeallweapons s24;
  removeallitems s24;
  removeBackpack s24;

  _s24playerweap = [
	 "M249_EP1",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	  "ItemWatch"
	 ];

  _s24playerammo = [
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "ACE_200Rnd_556x45_T_M249",
	 "ACE_200Rnd_556x45_T_M249",
	 "ACE_200Rnd_556x45_T_M249",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s24playerweapback = "";

  _s24playerweapruck = [];
  _s24playerammoruck = [];
  s24 setvariable ["ACE_weapononback", _s24playerweapback];
  {s24 addmagazine _x} foreach _s24playerammo;
  {s24 addWeapon _x} foreach _s24playerweap;

  s24 selectWeapon (primaryWeapon s24);

  removeallweapons s25;
  removeallitems s25;
  removeBackpack s25;

  _s25playerweap = [
	 "ACE_HK416_D10_Holo",
	 "ACE_Backpack_US",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	  "ItemWatch"
	 ];

  _s25playerammo = [
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "HandGrenade_West",
	 "HandGrenade_West",
	 "30Rnd_556x45_Stanag",
	 "30Rnd_556x45_Stanag",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s25playerweapback = "";

  _s25playerweapruck = [];
  _s25playerammoruck = [["ACE_200Rnd_556x45_T_M249",3]];
  s25 setvariable ["ACE_RuckMagContents", _s25playerammoruck];
  s25 setvariable ["ACE_weapononback", _s25playerweapback];
  {s25 addmagazine _x} foreach _s25playerammo;
  {s25 addWeapon _x} foreach _s25playerweap;

  s25 selectWeapon (primaryWeapon s25);

  removeallweapons s26;
  removeallitems s26;
  removeBackpack s26;

  _s26playerweap = [
	 "m107",
	 "ACE_USP",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	  "ItemWatch"
	 ];

  _s26playerammo = [
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "10Rnd_127x99_m107",
	 "10Rnd_127x99_m107",
	 "10Rnd_127x99_m107",
	 "10Rnd_127x99_m107",
	 "10Rnd_127x99_m107",
	 "ACE_12Rnd_45ACP_USP",
	  "ACE_12Rnd_45ACP_USP"
	 ];

  _s26playerweapback = "";

  _s26playerweapruck = [];
  _s26playerammoruck = [];
  s26 setvariable ["ACE_weapononback", _s26playerweapback];
  {s26 addmagazine _x} foreach _s26playerammo;
  {s26 addWeapon _x} foreach _s26playerweap;

  s26 selectWeapon (primaryWeapon s26);

  removeallweapons s27;
  removeallitems s27;
  removeBackpack s27;

  _s27playerweap = [
	 "ACE_M14_ACOG",
	 "ACE_Coyote_Pack",
	 "ACE_USP",
	 "Binocular_Vector",
	 "ACRE_PRC148_UHF",
	 "ACRE_PRC343",
	 "ItemCompass",
	 "ACE_KeyCuffs",
	 "ACE_Earplugs",
	 "ACE_GlassesGasMask_US",
	 "ItemGPS",
	 "ACE_HuntIR_monitor",
	  "ItemWatch"
	 ];

  _s27playerammo = [
	 "SmokeShellGreen",
	 "SmokeShellGreen",
	 "SmokeShellOrange",
	 "ACE_Battery_Rangefinder",
	 "20Rnd_762x51_DMR",
	 "20Rnd_762x51_DMR",
	 "20Rnd_762x51_DMR",
	 "20Rnd_762x51_DMR",
	 "20Rnd_762x51_DMR",
	 "20Rnd_762x51_DMR",
	 "20Rnd_762x51_DMR",
	 "ACE_HuntIR_M203",
	 "ACE_HuntIR_M203",
	 "ACE_12Rnd_45ACP_USP",
	 "ACE_12Rnd_45ACP_USP",
	 "1Rnd_HE_M203",
	 "1Rnd_HE_M203",
	  "1Rnd_Smoke_M203"
	 ];

  _s27playerweapback = "";

  _s27playerweapruck = [];
  _s27playerammoruck = [["10Rnd_127x99_m107",2]];
  s27 setvariable ["ACE_RuckMagContents", _s27playerammoruck];
  s27 setvariable ["ACE_weapononback", _s27playerweapback];
  {s27 addmagazine _x} foreach _s27playerammo;
  {s27 addWeapon _x} foreach _s27playerweap;

  s27 selectWeapon (primaryWeapon s27);

waitUntil {!isNil "ACE_fnc_PackIFAK"};
if (local player) then {
	[player, 2, 2, 1,true] call ACE_fnc_PackIFAK;
};

