// DO NOT EDIT THIS FILE
enableSaving [false,false];
setGroupIconsVisible [true,false]; //Show only 2D
enableCamShake true;
setViewDistance 2000;
setTerrainGrid 25;

// clients
if (!isDedicated) then {
	if (!isNil "fp_flag") then {
		[fp_flag,[["Alpha Actual","a0"],["Bravo Actual","b0"],["Charlie Actual","c0"],["Delta Actual","d0"]]] call compile preProcessFileLineNumbers "src\teleport.sqf";
	};
	{ _x setMarkerAlphaLocal 0; } foreach ["respawn_west","respawn_east","respawn_guer","respawn_guerrila","respawn_civilian","area"]; 
	// hide all area markers for UPS
	for "_i" from 0 to 50 do {
		_a = format ["area%1",_i];
		_a setMarkerAlphaLocal 0;
		_a = format ["area_%1",_i];
		_a setMarkerAlphaLocal 0;
	};
	[] spawn {
		waitUntil {!isNull player};
		// respawn with gear if using template gear
		player addEventHandler ["Respawn",{_this execVM "src\respawn.sqf"}];
		// deletes grenades thrown in spawn
		player addEventHandler ["Fired",
		{
			if (_this select 2 == "HandGrenadeMuzzle") then
			{
				if ((_this select 0) distance (markerPos (["respawn_west","respawn_east","respawn_guerrila","respawn_civilian"] select ([WEST,EAST,independent,civilian] find side player))) < 50) then
				{
					deleteVehicle (_this select 6);
					titleText ["G IS FOR GRENADES", "PLAIN", 3];
				};
			};
		}];
		sleep  0.3;
		// lower weapon
		player switchMove "amovpercmstpslowwrfldnon";
		while {true} do {
			waitUntil {sleep 1; alive player};
			if (rating player < 0) then {
				player addRating (abs(rating player));
			};
		};
	};
};

// server
if (isServer) then 
{
	createCenter west;
	createCenter east;
	createCenter resistance;
	createCenter civilian;

	// start garbage collector
	if (isNil "FP_gc_queue") then {
		FP_gc_queue = [];
		[] execVM "src\spawn\cleanup\fn_GCprocess.sqf";
	};
};