#define PREFIX CUC
#define CUSTOM_FOLDER components\COMPONENT

#define MAJOR 0
#define MINOR 1
#define PATCHLVL 0
#define BUILD 0

#define VERSION MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR MAJOR,MINOR,PATCHLVL,BUILD

#define REQUIRED_VERSION 1.58
