leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.
"tankspawnmarker" setmarkeralphalocal 0;
"respawn_west" setmarkeralphalocal 0;
"a" setmarkersizelocal [0.5,0.5];
//======= Player is player ======
if ((!isServer) && (player != player)) then {waitUntil {player == player};};

//Enable AI Hearing you speak on ACRE
if (!isDedicated) then {[] execVM "source\aiHearTalking.sqf"; };

//======= ACE SETTINGS ======
//AI has no medical gear , true/false
ace_sys_wounds_no_rpunish = true;
ace_sys_wounds_leftdam  = 0.2;
ace_wounds_prevtime = 400;

//Do not store weapons in helis/planes. Keep everything on the player.
if (isServer) then { ace_sys_eject_fnc_weaponCheckEnabled = {false}; 
	publicVariable "ace_sys_eject_fnc_weaponCheckEnabled";
	spawningDone = true; publicVariable "spawningDone";
	onPlayerConnected ' if(time > 60) then { "train1" setMarkerColor (getMarkerColor "train1"); "train2" setMarkerColor (getMarkerColor "train2"); "train3" setMarkerColor (getMarkerColor "train3");};'; 
};


//======= Turn off a bunch of BIS stuff ======
//Disable Saving and Auto Saving
enableSaving [false, false];

//Bury player script
if (!isdedicated) then
{
	player setVariable ["BIS_noCoreConversations", true];
	waitUntil {!isNull player};
	player addEventHandler ["killed",{nul=_this execVM "source\burial.sqf"}];
	player switchMove "amovpercmstpslowwrfldnon_player_idlesteady03";  
};

//====== Time to start the mission! ======
//Process statements stored using setVehicleInit
processInitCommands;

//Finish world initialization before mission is launched. 
finishMissionInit;
//Lower players weapon at the start of a mission
player switchMove "amovpercmstpslowwrfldnon_player_idlesteady03";  
