leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.
if ((!isServer) && (player != player)) then {
	waitUntil {player == player};
};

ace_sys_wounds_leftdam  = 0.3;
ace_wounds_prevtime = 400;
ace_sys_wounds_no_rpunish = true;

enableSaving [false, false];

if (isServer) then {
	civsRescued = 0;
	publicVariable "civsRescued";
	onPlayerConnected ' "respawn_west" setmarkerpos (getmarkerpos "respawn_west");'; 
	ace_sys_eject_fnc_weaponCheckEnabled = {false}; 
	publicVariable "ace_sys_eject_fnc_weaponCheckEnabled";
};

[[
  ["task1", "Clear Shamali and free hostages","<br><br/>Your first objective is to launch a quick assault on Shamali with the intention of freeing three civilians that was captured and held for ransom by insurgents.",true,["task1mark",(getMarkerPos "firstobj"),"Attack","ColorRed"," Clear & free hostages"]],
  ["task2", "Take control of the oil field","<br><br/>Insurgents have for a long time occupied the oil field SW of Shamali. We need to recapture it for the Takistani people.",true,["task2mark",(getPosATL z1),"FireMission","ColorRed"," Take control of oil field"]],
  ["task3", "Search ammo caches in Nagara","<br><br/>Recon suggests that insurgents has ammo and weapons in Nagara. We need to find these ammo caches and destroy them.",true,["task3mark",(getPosATL z2),"FireMission","ColorRed"," Cache search"]]

  ],[
  ["Mission", "Your task today as a quick strike force is to clear Shamali of insurgents and free three captuerd hostages in the location. After that, proceed to the oil field and get rid of all insurgents in the area. Shall you succeed, your last task will be to clear Nagara of enemies and destroy any weapon caches that you can find."]
]] execvm "shk_taskmaster.sqf";

processInitCommands;
finishMissionInit;
setViewDistance 2000;
setTerrainGrid 25;

if (!isDedicated) then {
	player setVariable ["BIS_noCoreConversations", true];
	player switchMove "amovpercmstpslowwrfldnon_player_idlesteady03";  
};

0 fadeSound 0;
cutText ["","BLACK FADED",3];
sleep 1;
cutText ["","BLACK IN",3];
3 fadeSound 1;


if (time > 60) then {
	sleep 5;
	if ( "task1" call SHK_Taskmaster_isCompleted) then {
		player setPos (getmarkerpos "respawn_west");
	};
};
